# One-click host launcher for a self-hosted Missile Wars shard (Windows).
#
# PowerShell equivalent of docker/host.sh:
#   1. Checks Docker Desktop + compose are installed (with install links).
#   2. Generates .env with local secrets on first launch (setup.sh equivalent).
#   3. Optionally registers this shard with the coordinator and saves
#      COORDINATOR_URL + SHARD_API_KEY into .env.
#   4. Starts the stack: docker compose up -d --build
#   5. Verifies /healthz locally and probes public reachability.
#
# Usage:  .\docker\host.ps1   (from anywhere; works in Windows PowerShell 5.1+)
$ErrorActionPreference = "Stop"

Set-Location (Join-Path $PSScriptRoot "..")

function Write-Ok($msg)   { Write-Host "[OK]   $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Write-Fail($msg) { Write-Host "[FAIL] $msg" -ForegroundColor Red }
function Write-Step($msg) { Write-Host "`n$msg" -ForegroundColor Cyan }

# ---------------------------------------------------------------- step 1: deps
Write-Step "1/5 Checking Docker..."

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Fail "Docker is not installed."
    Write-Host "  Install Docker Desktop for Windows:"
    Write-Host "    https://docs.docker.com/desktop/setup/install/windows-install/"
    Write-Host "  Then re-run .\docker\host.ps1"
    exit 1
}

docker info *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Fail "Docker is installed but not running."
    Write-Host "  Start Docker Desktop and wait for it to say 'running', then re-run this script."
    exit 1
}

docker compose version *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Fail "The 'docker compose' plugin is missing (Docker Desktop normally includes it)."
    Write-Host "  Install it: https://docs.docker.com/compose/install/"
    exit 1
}
Write-Ok "Docker is ready"

# ------------------------------------------------------------- step 2: secrets
Write-Step "2/5 Local secrets (.env)..."

function New-RandomHex {
    $bytes = New-Object byte[] 32
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    $rng.Dispose()
    return ([System.BitConverter]::ToString($bytes) -replace '-', '').ToLower()
}

if (Test-Path .env) {
    Write-Ok ".env already exists - keeping it"
} else {
    $pgPassword = New-RandomHex
    $jwtSecret = New-RandomHex
    $stamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $envContent = @"
# Generated by docker/host.ps1 on $stamp.
# These secrets are local to THIS shard - never share or reuse them.

# Public port the shard listens on.
PORT=8080

# Local Postgres (runs in the db container; data in the db-data volume).
POSTGRES_USER=missilewars
POSTGRES_DB=missilewars
POSTGRES_PASSWORD=$pgPassword

# Local JWT secret (interim - replaced by coordinator-issued public keys in a
# later phase of the distributed-hosting plan).
JWT_SECRET=$jwtSecret

# Set to ON for chatty logs.
VERBOSE_MODE=OFF

# --- Distributed hosting (fill in once registered with the coordinator) ---
#COORDINATOR_URL=
#SHARD_API_KEY=

# --- Optional: password-reset emails (moves to coordinator later) ---
#EMAIL_HOST=
#EMAIL_PORT=587
#EMAIL_SECURE=false
#EMAIL_USER=
#EMAIL_PASS=
#EMAIL_FROM=
"@
    # UTF-8 without BOM - docker compose cannot parse a BOM on the first line.
    [System.IO.File]::WriteAllText((Join-Path (Get-Location) ".env"), $envContent, (New-Object System.Text.UTF8Encoding($false)))
    Write-Ok "Wrote .env with locally generated secrets"
}

function Get-EnvValue($key) {
    $line = Get-Content .env | Where-Object { $_ -match "^\s*$key=" } | Select-Object -Last 1
    if ($null -eq $line) { return "" }
    return ($line -replace "^\s*$key=", "").Trim()
}

$port = Get-EnvValue "PORT"
if (-not $port) { $port = "8080" }

# -------------------------------------------------------- step 3: registration
Write-Step "3/5 Coordinator registration (optional)..."

$coordinatorUrl = Get-EnvValue "COORDINATOR_URL"
$shardApiKey = Get-EnvValue "SHARD_API_KEY"

if ($coordinatorUrl -and $shardApiKey) {
    Write-Ok "Already registered (COORDINATOR_URL + SHARD_API_KEY set) - heartbeats enabled"
} else {
    $reply = Read-Host "Register this shard with a coordinator so players can discover it? [y/N]"
    if ($reply -eq "y" -or $reply -eq "Y") {
        $publicIp = ""
        try { $publicIp = (Invoke-RestMethod -Uri "https://api.ipify.org" -TimeoutSec 5) } catch {}

        $regCoord = (Read-Host "Coordinator URL (e.g. https://coordinator.example.com)").TrimEnd("/")
        $regName = Read-Host "Shard name (shown to players)"
        $regRegion = Read-Host "Region (e.g. eu-west, us-east)"
        if ($publicIp) { $defaultHttp = "http://${publicIp}:${port}" } else { $defaultHttp = "http://YOUR_PUBLIC_IP:${port}" }
        $regHttp = Read-Host "Public HTTP URL [$defaultHttp]"
        if (-not $regHttp) { $regHttp = $defaultHttp }
        $defaultWs = $regHttp -replace "^http", "ws"
        $regWs = Read-Host "Public WebSocket URL [$defaultWs]"
        if (-not $regWs) { $regWs = $defaultWs }
        $regContact = Read-Host "Owner contact (email/discord, optional)"

        $body = @{
            name = $regName
            region = $regRegion
            publicHttpUrl = $regHttp
            publicWsUrl = $regWs
            ownerContact = $regContact
        } | ConvertTo-Json

        Write-Host "Registering with $regCoord ..."
        try {
            $response = Invoke-RestMethod -Uri "$regCoord/shards/register" -Method Post `
                -ContentType "application/json" -Body $body -TimeoutSec 15
            $apiKey = $response.data.apiKey
            $shardId = $response.data.shardId
            if ($apiKey) {
                $append = "`n# Coordinator registration (written by docker/host.ps1; key shown once by the coordinator)`n"
                $append += "COORDINATOR_URL=$regCoord`n"
                $append += "SHARD_API_KEY=$apiKey`n"
                $append += "SHARD_ID=$shardId`n"
                [System.IO.File]::AppendAllText((Join-Path (Get-Location) ".env"), $append, (New-Object System.Text.UTF8Encoding($false)))
                Write-Ok "Registered (shard id: $shardId). API key saved to .env - it is revocable and safe to keep here."
            } else {
                Write-Fail "Unexpected response from coordinator:"
                Write-Host ($response | ConvertTo-Json -Depth 5)
            }
        } catch {
            Write-Fail "Registration failed - check the coordinator URL and try again later."
            Write-Host "  The shard will still start; re-run .\docker\host.ps1 to retry."
        }
    } else {
        Write-Host "Skipping - the shard runs standalone. Re-run .\docker\host.ps1 any time to register."
    }
}

# ------------------------------------------------------------- step 4: launch
Write-Step "4/5 Starting the shard (this builds the image on first run)..."
docker compose up -d --build
if ($LASTEXITCODE -ne 0) {
    Write-Fail "docker compose failed - see output above."
    exit 1
}

# ------------------------------------------------------- step 5: reachability
Write-Step "5/5 Checking the shard is reachable..."

$healthy = $false
for ($i = 0; $i -lt 30; $i++) {
    try {
        $null = Invoke-WebRequest -Uri "http://localhost:${port}/healthz" -TimeoutSec 2 -UseBasicParsing
        $healthy = $true
        break
    } catch {
        Start-Sleep -Seconds 2
    }
}

if ($healthy) {
    Write-Ok "Shard is up locally: http://localhost:${port}/healthz"
} else {
    Write-Fail "Shard did not become healthy within 60s."
    Write-Host "  Inspect logs with: docker compose logs -f backend"
    exit 1
}

$publicIp = ""
try { $publicIp = (Invoke-RestMethod -Uri "https://api.ipify.org" -TimeoutSec 5) } catch {}

if (-not $publicIp) {
    Write-Warn "Could not determine your public IP - skipping the port-forwarding check."
} else {
    $publicOk = $false
    try {
        $null = Invoke-WebRequest -Uri "http://${publicIp}:${port}/healthz" -TimeoutSec 8 -UseBasicParsing
        $publicOk = $true
    } catch {}
    if ($publicOk) {
        Write-Ok "Publicly reachable!  Players connect via: http://${publicIp}:${port}"
    } else {
        Write-Warn "Could not reach http://${publicIp}:${port}/healthz from this machine."
        Write-Host "  Port $port looks closed from the internet. To fix:"
        Write-Host "   - Home network: forward TCP $port to this machine on your router."
        Write-Host "   - Also allow it in Windows Defender Firewall (inbound TCP $port)."
        Write-Host "   - VPS/cloud:    open TCP $port in the provider firewall/security group."
        Write-Host "  Note: some home routers block 'hairpin' connections from inside the same"
        Write-Host "  network, so this probe can be a false negative - ask someone outside your"
        Write-Host "  network to open the URL above to confirm."
    }
}

Write-Host ""
Write-Step "Done. Useful commands:"
Write-Host "  docker compose logs -f backend    # tail server logs"
Write-Host "  docker compose down               # stop (DB data persists)"
Write-Host "  .\docker\host.ps1                 # restart / re-check any time"
