# One-click host launcher for a self-hosted Missile Wars shard (Windows).
#
# PowerShell equivalent of docker/host.sh:
#   1. Checks Docker Desktop + compose are installed (with install links).
#   2. Generates .env with local secrets on first launch (setup.sh equivalent).
#   3. Registers this shard with the official coordinator and saves
#      COORDINATOR_URL + SHARD_API_KEY into .env.
#   4. Starts the stack: docker compose up -d --build
#   5. Verifies /healthz locally and probes public reachability.
#
# Usage:  .\docker\host.ps1   (from anywhere; works in Windows PowerShell 5.1+)
$ErrorActionPreference = "Stop"

Set-Location (Join-Path $PSScriptRoot "..")

$OfficialCoordinatorUrl = "https://backend-coordinator.vercel.app"

function Write-Ok($msg)   { Write-Host "[OK]   $msg" -ForegroundColor Green }
function Write-Warn($msg) { Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Write-Fail($msg) { Write-Host "[FAIL] $msg" -ForegroundColor Red }
function Write-Step($msg) { Write-Host "`n$msg" -ForegroundColor Cyan }

# ---------------------------------------------------------------- step 1: deps
Write-Step "1/5 Checking Docker..."

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    Write-Fail "Docker is not installed."
    Write-Host "  Install Docker Desktop for Windows:"
    Write-Host "    https://docs.docker.com/desktop/setup/install/windows-install/"
    Write-Host "  Then re-run .\docker\host.ps1"
    exit 1
}

docker info *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Fail "Docker is installed but not running."
    Write-Host "  Start Docker Desktop and wait for it to say 'running', then re-run this script."
    exit 1
}

docker compose version *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Fail "The 'docker compose' plugin is missing (Docker Desktop normally includes it)."
    Write-Host "  Install it: https://docs.docker.com/compose/install/"
    exit 1
}
Write-Ok "Docker is ready"

# ------------------------------------------------------------- step 2: secrets
Write-Step "2/5 Local secrets (.env)..."

function New-RandomHex {
    $bytes = New-Object byte[] 32
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $rng.GetBytes($bytes)
    $rng.Dispose()
    return ([System.BitConverter]::ToString($bytes) -replace '-', '').ToLower()
}

if (Test-Path .env) {
    Write-Ok ".env already exists - keeping it"
} else {
    $pgPassword = New-RandomHex
    $jwtSecret = New-RandomHex
    $stamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $envContent = @"
# Generated by docker/host.ps1 on $stamp.
# These secrets are local to THIS shard - never share or reuse them.

# Public port the shard listens on.
PORT=8080

# Local Postgres (runs in the db container; data in the db-data volume).
POSTGRES_USER=missilewars
POSTGRES_DB=missilewars
POSTGRES_PASSWORD=$pgPassword

# Local JWT secret (interim - replaced by coordinator-issued public keys in a
# later phase of the distributed-hosting plan).
JWT_SECRET=$jwtSecret

# Set to ON for chatty logs.
VERBOSE_MODE=OFF

# --- Distributed hosting (written by docker/host.ps1 after registration) ---
#COORDINATOR_URL=https://backend-coordinator.vercel.app
#SHARD_API_KEY=
#SHARD_ID=

# --- Optional: password-reset emails (moves to coordinator later) ---
#EMAIL_HOST=
#EMAIL_PORT=587
#EMAIL_SECURE=false
#EMAIL_USER=
#EMAIL_PASS=
#EMAIL_FROM=
"@
    # UTF-8 without BOM - docker compose cannot parse a BOM on the first line.
    [System.IO.File]::WriteAllText((Join-Path (Get-Location) ".env"), $envContent, (New-Object System.Text.UTF8Encoding($false)))
    Write-Ok "Wrote .env with locally generated secrets"
}

function Get-EnvValue($key) {
    $line = Get-Content .env | Where-Object { $_ -match "^\s*$key=" } | Select-Object -Last 1
    if ($null -eq $line) { return "" }
    return ($line -replace "^\s*$key=", "").Trim()
}

$port = Get-EnvValue "PORT"
if (-not $port) { $port = "8080" }

# -------------------------------------------------------- step 3: registration
Write-Step "3/5 Official coordinator registration..."

$coordinatorUrl = Get-EnvValue "COORDINATOR_URL"
$shardApiKey = Get-EnvValue "SHARD_API_KEY"

function Read-Required($prompt) {
    do {
        $value = Read-Host $prompt
        if (-not $value) { Write-Warn "Please type something here. Empty answers cannot be registered." }
    } while (-not $value)
    return $value
}

function Read-AvailableName($coordinatorUrl) {
    do {
        $value = Read-Required "Server name players will see (example: Official Main)"
        try {
            $encodedName = [System.Uri]::EscapeDataString($value)
            $result = Invoke-RestMethod -Uri "$coordinatorUrl/shards/name-available?name=$encodedName" -TimeoutSec 10
            if ($result.data.available) {
                return $value
            }
            Write-Warn "That server name is already taken. Pick a different name."
            $value = ""
        } catch {
            Write-Warn "Could not check that name right now. Registration will still verify it at the end."
            return $value
        }
    } while (-not $value)
}

function Read-Region {
    $regions = @(
        "us-east", "us-west", "canada", "south-america",
        "eu-west", "eu-central", "uk", "africa",
        "asia", "australia"
    )
    $other = $regions.Count + 1
    Write-Host "Region - pick the location closest to your server:"
    for ($i = 0; $i -lt $regions.Count; $i++) {
        Write-Host ("  {0,2}. {1}" -f ($i + 1), $regions[$i])
    }
    Write-Host ("  {0,2}. Other (type your own)" -f $other)
    while ($true) {
        $choice = Read-Host "Enter a number 1-$other"
        $n = 0
        if ([int]::TryParse($choice, [ref]$n) -and $n -ge 1 -and $n -le $other) {
            if ($n -eq $other) {
                return (Read-Required "Custom region label (example: me-central, sa-east)")
            }
            return $regions[$n - 1]
        }
        Write-Warn "Please enter a number between 1 and $other."
    }
}

function Read-OwnerEmail {
    do {
        $value = Read-Host "Owner contact email (required, example: you@example.com)"
        if ($value -notmatch "^[^@\s]+@[^@\s]+\.[^@\s]+$") {
            Write-Warn "Please enter an email address with an @ and a domain. This lets admins contact you if your server breaks."
            $value = ""
        }
    } while (-not $value)
    return $value
}

if ($coordinatorUrl -and $shardApiKey) {
    Write-Ok "Already registered (COORDINATOR_URL + SHARD_API_KEY set) - heartbeats enabled"
} else {
    $regCoord = $OfficialCoordinatorUrl
    $publicIp = ""
    try { $publicIp = (Invoke-RestMethod -Uri "https://api.ipify.org" -TimeoutSec 5) } catch {}

    Write-Host "This server must introduce itself to the Missile Wars backend coordinator:"
    Write-Host "  $regCoord/shards/register"
    Write-Host ""
    Write-Host "Use real public details here. The phone app will copy these values later."
    Write-Host "Do not use localhost, 127.0.0.1, db, backend, or a Docker container name."
    Write-Host ""

    $regName = Read-AvailableName $regCoord
    $regRegion = Read-Region

    if ($publicIp) { $defaultHttp = "http://${publicIp}:${port}" } else { $defaultHttp = "http://YOUR_PUBLIC_IP:${port}" }
    Write-Host ""
    Write-Host "Public HTTP URL:"
    Write-Host "  This is the normal web address for this backend from OUTSIDE this computer."
    Write-Host "  If you bought a domain and set up HTTPS, use that, for example:"
    Write-Host "    https://play.example.com"
    Write-Host "  If this is a VPS or home server without a domain, this script guessed:"
    Write-Host "    $defaultHttp"
    Write-Host "  The guessed IP comes from the internet seeing this machine. If your router"
    Write-Host "  forwards a different port, or your cloud provider gave you a DNS name, type"
    Write-Host "  the correct full URL instead. Include http:// or https:// at the front."
    $regHttp = Read-Host "Public HTTP URL [$defaultHttp]"
    if (-not $regHttp) { $regHttp = $defaultHttp }

    $defaultWs = $regHttp -replace "^https", "wss"
    $defaultWs = $defaultWs -replace "^http", "ws"
    Write-Host ""
    Write-Host "Public WebSocket URL:"
    Write-Host "  This is usually the same address with ws:// instead of http://, or wss://"
    Write-Host "  instead of https://. The default below is normally correct."
    $regWs = Read-Host "Public WebSocket URL [$defaultWs]"
    if (-not $regWs) { $regWs = $defaultWs }

    $regContact = Read-OwnerEmail

    $body = @{
        name = $regName
        region = $regRegion
        publicHttpUrl = $regHttp
        publicWsUrl = $regWs
        ownerContact = $regContact
    } | ConvertTo-Json

    Write-Host "Registering with $regCoord ..."
    try {
        $response = Invoke-RestMethod -Uri "$regCoord/shards/register" -Method Post `
            -ContentType "application/json" -Body $body -TimeoutSec 15
        $apiKey = $response.data.apiKey
        $shardId = $response.data.shardId
        if ($apiKey) {
            $append = "`n# Coordinator registration (written by docker/host.ps1; key shown once by the coordinator)`n"
            $append += "COORDINATOR_URL=$regCoord`n"
            $append += "SHARD_API_KEY=$apiKey`n"
            $append += "SHARD_ID=$shardId`n"
            [System.IO.File]::AppendAllText((Join-Path (Get-Location) ".env"), $append, (New-Object System.Text.UTF8Encoding($false)))
            Write-Ok "Registered (shard id: $shardId). API key saved to .env - it is revocable and safe to keep here."
        } else {
            Write-Fail "Unexpected response from coordinator:"
            Write-Host ($response | ConvertTo-Json -Depth 5)
            exit 1
        }
    } catch {
        Write-Fail "Registration failed - check the public URLs and try again."
        Write-Host "  Nothing was saved to .env. Re-run .\docker\host.ps1 to retry."
        exit 1
    }
}

# ------------------------------------------------------------- step 4: launch
Write-Step "4/5 Starting the shard (this builds the image on first run)..."
docker compose up -d --build
if ($LASTEXITCODE -ne 0) {
    Write-Fail "docker compose failed - see output above."
    exit 1
}

# ------------------------------------------------------- step 5: reachability
Write-Step "5/5 Checking the shard is reachable..."

$healthy = $false
for ($i = 0; $i -lt 30; $i++) {
    try {
        $null = Invoke-WebRequest -Uri "http://localhost:${port}/healthz" -TimeoutSec 2 -UseBasicParsing
        $healthy = $true
        break
    } catch {
        Start-Sleep -Seconds 2
    }
}

if ($healthy) {
    Write-Ok "Shard is up locally: http://localhost:${port}/healthz"
} else {
    Write-Fail "Shard did not become healthy within 60s."
    Write-Host "  Inspect logs with: docker compose logs -f backend"
    exit 1
}

$publicIp = ""
try { $publicIp = (Invoke-RestMethod -Uri "https://api.ipify.org" -TimeoutSec 5) } catch {}

if (-not $publicIp) {
    Write-Warn "Could not determine your public IP - skipping the port-forwarding check."
} else {
    $publicOk = $false
    try {
        $null = Invoke-WebRequest -Uri "http://${publicIp}:${port}/healthz" -TimeoutSec 8 -UseBasicParsing
        $publicOk = $true
    } catch {}
    if ($publicOk) {
        Write-Ok "Publicly reachable!  Players connect via: http://${publicIp}:${port}"
    } else {
        Write-Warn "Could not reach http://${publicIp}:${port}/healthz from this machine."
        Write-Host "  Port $port looks closed from the internet. To fix:"
        Write-Host "   - Home network: forward TCP $port to this machine on your router."
        Write-Host "   - Also allow it in Windows Defender Firewall (inbound TCP $port)."
        Write-Host "   - VPS/cloud:    open TCP $port in the provider firewall/security group."
        Write-Host "  Note: some home routers block 'hairpin' connections from inside the same"
        Write-Host "  network, so this probe can be a false negative - ask someone outside your"
        Write-Host "  network to open the URL above to confirm."
    }
}

Write-Host ""
Write-Step "Done. Useful commands:"
Write-Host "  docker compose logs -f backend    # tail server logs"
Write-Host "  docker compose down               # stop (DB data persists)"
Write-Host "  .\docker\host.ps1                 # restart / re-check any time"
