#!/usr/bin/env bash
# First-run setup for a self-hosted Missile Wars shard.
#
# Generates a .env next to docker-compose.yml with locally generated secrets
# (Postgres password, JWT secret), so no secret is ever shared between shard
# hosts. Safe to re-run: it refuses to overwrite an existing .env.
#
# Usage:  ./docker/setup.sh   (from the backend repo root)
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
    echo ".env already exists — leaving it untouched."
    echo "Start the shard with: docker compose up -d --build"
    exit 0
fi

rand_hex() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

POSTGRES_PASSWORD="$(rand_hex)"
JWT_SECRET="$(rand_hex)"

cat > .env <<EOF
# Generated by docker/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# These secrets are local to THIS shard — never share or reuse them.

# Public port the shard listens on.
PORT=8080

# Local Postgres (runs in the db container; data in the db-data volume).
POSTGRES_USER=missilewars
POSTGRES_DB=missilewars
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Local JWT secret (interim — replaced by coordinator-issued public keys in a
# later phase of the distributed-hosting plan).
JWT_SECRET=${JWT_SECRET}

# Set to ON for chatty logs.
VERBOSE_MODE=OFF

# --- Distributed hosting (fill in once registered with the coordinator) ---
#COORDINATOR_URL=
#SHARD_API_KEY=

# --- Optional: password-reset emails (moves to coordinator later) ---
#EMAIL_HOST=
#EMAIL_PORT=587
#EMAIL_SECURE=false
#EMAIL_USER=
#EMAIL_PASS=
#EMAIL_FROM=
EOF

chmod 600 .env
echo "Wrote .env with locally generated secrets."
echo "Start the shard with: docker compose up -d --build"
