#!/usr/bin/env bash
# First-run setup for a self-hosted Missile Wars shard.
#
# Generates or repairs a .env next to docker-compose.yml with locally generated
# secrets (Postgres password, JWT secret), so no secret is ever shared between
# shard hosts. Safe to re-run: it preserves existing values and only appends
# missing Docker-required keys.
#
# Usage:  ./docker/setup.sh   (from the backend repo root)
set -euo pipefail

cd "$(dirname "$0")/.."

rand_hex() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

env_get() {
    if [ ! -f .env ]; then
        return 0
    fi
    sed -n "s/^[[:space:]]*$1=//p" .env | tail -n 1
}

env_has_value() {
    value="$(env_get "$1")"
    [ -n "$value" ]
}

append_env() {
    key="$1"
    value="$2"
    if ! env_has_value "$key"; then
        if [ "$REPAIR_HEADER_WRITTEN" != "1" ]; then
            {
                echo ""
                echo "# Docker shard defaults repaired by docker/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
            } >> .env
            REPAIR_HEADER_WRITTEN=1
        fi
        printf '%s=%s\n' "$key" "$value" >> .env
        echo "Added missing $key to .env"
    fi
}

if [ ! -f .env ]; then
    POSTGRES_PASSWORD="$(rand_hex)"
    JWT_SECRET="$(rand_hex)"

    cat > .env <<EOF
# Generated by docker/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# These secrets are local to THIS shard — never share or reuse them.

# Public port the shard listens on.
PORT=8080

# Local Postgres (runs in the db container; data in the db-data volume).
POSTGRES_USER=missilewars
POSTGRES_DB=missilewars
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

# Local JWT secret (interim — replaced by coordinator-issued public keys in a
# later phase of the distributed-hosting plan).
JWT_SECRET=${JWT_SECRET}

# Set to ON for chatty logs.
VERBOSE_MODE=OFF

# --- Distributed hosting (written by docker/host.sh after registration) ---
#COORDINATOR_URL=https://backend-coordinator.vercel.app
#SHARD_API_KEY=
#SHARD_ID=

# --- Optional: password-reset emails (moves to coordinator later) ---
#EMAIL_HOST=
#EMAIL_PORT=587
#EMAIL_SECURE=false
#EMAIL_USER=
#EMAIL_PASS=
#EMAIL_FROM=
EOF
    chmod 600 .env
    echo "Wrote .env with locally generated secrets."
    echo "Start the shard with: docker compose up -d --build"
    exit 0
fi

echo ".env already exists - checking Docker-required values."
REPAIR_HEADER_WRITTEN=0
append_env "PORT" "8080"
append_env "POSTGRES_USER" "missilewars"
append_env "POSTGRES_DB" "missilewars"
append_env "POSTGRES_PASSWORD" "$(rand_hex)"
append_env "JWT_SECRET" "$(rand_hex)"
append_env "VERBOSE_MODE" "OFF"
chmod 600 .env
echo ".env is ready for Docker."
echo "Start the shard with: docker compose up -d --build"
